apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora-api
  template:
    metadata:
      labels:
        app: lora-api
    spec:
      containers:
        - name: lora-api
          image: lora-inference:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
